# Generated by Django 3.2 on 2021-05-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='限界で1行52文字、5行以内なのでそれ以上だとおかしくなります！（とにかく簡潔に！いっぱい書くと崩れる！）'),
        ),
    ]
